image: python3.5
stages:
  - documentation
  - deploy

mkdocs_build:
  stage: documentation
  script:
    - pip install -r requirements-doc.txt
    - mkdocs build
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - mkdocs_build
  script:
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master
