# Generated by Django 2.0.5 on 2020-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_link_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='pending',
            field=models.BooleanField(default=True, verbose_name='pending'),
        ),
    ]
