# Generated by Django 2.0.5 on 2020-03-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20200329_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot/', verbose_name='screenshot'),
        ),
    ]
