# Generated by Django 2.0.5 on 2020-03-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_link_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='screenshot',
            field=models.ImageField(default='screenshot/not-found.png', upload_to='screenshot/', verbose_name='screenshot'),
        ),
    ]
